name: 🚀 Feature request
description: Propose a new feature
labels: []
type: 'feature'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature 💜
        Please fill out the form below to help us understand and consider your proposal.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Specify context of the current situation. Write a clear and concise description of what the feature is. Provide your thoughts on the solution.
      placeholder: Feature description...
      value: |
        Context: ...
        Feature description: ...
        Suggested solution: ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
      placeholder: Additional information
    validations:
      required: false
